version: "3.9"
services:
  database:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sad-db
      - POSTGRES_PASSWORD=ZsJPg3pVtHFMXaE
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-tier
  server:
    build:
      context: .
    image:
      010573/talent:latest
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - app-tier
volumes:
  data:
networks:
  app-tier:
    driver: bridge