name: devcamp-pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test

  build_and_push_images:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          username: '010573'
          password: '3e287b28-49cd-44bc-bf20-0f6006064104'
          repository: 010573/devcamp
          tags: latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_images
    steps:
      - name: Connect SSH
        uses: appleboy/ssh-action@master
        with:
          host: 20.70.234.83
          username: devcamp
          password: NinjaDragon123
          port: 22
          script: |
            cd ~/devcamp-api
            git pull origin dev
            echo 'NinjaDragon123' | sudo -S docker-compose -f docker-compose.prod.yml stop
            echo 'NinjaDragon123' | sudo -S docker pull 010573/devcamp:latest
            echo 'NinjaDragon123' | sudo -S docker-compose -f docker-compose.prod.yml up --build -d